apiVersion: v1
kind: Pod
metadata:
  name: trap-exec
  labels:
    app: exec
spec:
  terminationGracePeriodSeconds: 10 # default is 30
  containers:
  - name: trap
    image: trap:exec
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command: ["echo", "Executando preStop Hook"]
